// Offline verse data for the Bible Verse bar widget.
// Fully local — no network, no API. The verses are wired in here so the
// widget and its popup never leave the machine.
//
// Each verse is stored as { ref: "citation", text: "…" }. The bar shows the
// citation; the popup shows the full text alongside the citation.

var VERSES = [
  { ref: "John 3:16", text: "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life." },
  { ref: "Philippians 4:13", text: "I can do all things through Christ which strengtheneth me." },
  { ref: "Proverbs 3:5", text: "Trust in the Lord with all thine heart; and lean not unto thine own understanding." },
  { ref: "Jeremiah 29:11", text: "For I know the thoughts that I think toward you, saith the Lord, thoughts of peace, and not of evil, to give you an expected end." },
  { ref: "Psalm 23:1", text: "The Lord is my shepherd; I shall not want." },
  { ref: "Isaiah 41:10", text: "Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness." },
  { ref: "Romans 8:28", text: "And we know that all things work together for good to them that love God, to them who are the called according to his purpose." },
  { ref: "Psalm 46:10", text: "Be still, and know that I am God." },
  { ref: "Matthew 11:28", text: "Come unto me, all ye that labour and are heavy laden, and I will give you rest." },
  { ref: "Joshua 1:9", text: "Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the Lord thy God is with thee whithersoever thou goest." },
  { ref: "Psalm 91:1", text: "He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty." },
  { ref: "1 Corinthians 13:4", text: "Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up." },
  { ref: "Galatians 5:22", text: "But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith." },
  { ref: "Psalm 119:105", text: "Thy word is a lamp unto my feet, and a light unto my path." },
  { ref: "Matthew 6:33", text: "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you." },
  { ref: "2 Timothy 1:7", text: "For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind." },
  { ref: "Psalm 34:18", text: "The Lord is nigh unto them that are of a broken heart; and saveth such as be of a contrite spirit." },
  { ref: "John 14:6", text: "Jesus saith unto him, I am the way, the truth, and the life: no man cometh unto the Father, but by me." },
  { ref: "Isaiah 40:31", text: "But they that wait upon the Lord shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint." },
  { ref: "Romans 12:2", text: "And be not conformed to this world: but be ye transformed by the renewing of your mind, that ye may prove what is that good, and acceptable, and perfect, will of God." },
  { ref: "Psalm 37:4", text: "Delight thyself also in the Lord; and he shall give thee the desires of thine heart." },
  { ref: "Matthew 5:16", text: "Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven." },
  { ref: "1 Peter 5:7", text: "Casting all your care upon him; for he careth for you." },
  { ref: "Hebrews 11:1", text: "Now faith is the substance of things hoped for, the evidence of things not seen." },
  { ref: "Psalm 27:1", text: "The Lord is my light and my salvation; whom shall I fear? The Lord is the strength of my life; of whom shall I be afraid?" },
  { ref: "James 1:5", text: "If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him." },
  { ref: "Proverbs 3:6", text: "In all thy ways acknowledge him, and he shall direct thy paths." },
  { ref: "Psalm 103:2", text: "Bless the Lord, O my soul, and forget not all his benefits." },
  { ref: "Micah 6:8", text: "He hath shewed thee, O man, what is good; and what doth the Lord require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?" },
  { ref: "Philippians 4:6", text: "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God." },
  { ref: "Psalm 139:14", text: "I will praise thee; for I am fearfully and wonderfully made: marvellous are thy works; and that my soul knoweth right well." },
  { ref: "John 8:32", text: "And ye shall know the truth, and the truth shall make you free." },
  { ref: "Romans 5:8", text: "But God commendeth his love toward us, in that, while we were yet sinners, Christ died for us." },
  { ref: "Psalm 118:24", text: "This is the day which the Lord hath made; we will rejoice and be glad in it." },
  { ref: "Isaiah 26:3", text: "Thou wilt keep him in perfect peace, whose mind is stayed on thee: because he trusteth in thee." },
  { ref: "1 John 4:19", text: "We love him, because he first loved us." },
  { ref: "Psalm 46:1", text: "God is our refuge and strength, a very present help in trouble." },
  { ref: "Matthew 6:34", text: "Take therefore no thought for the morrow: for the morrow shall take thought for the things of itself." },
  { ref: "Proverbs 16:3", text: "Commit thy works unto the Lord, and thy thoughts shall be established." },
  { ref: "Zephaniah 3:17", text: "The Lord thy God in the midst of thee is mighty; he will save, he will rejoice over thee with joy; he will rest in his love, he will joy over thee with singing." },
  { ref: "Genesis 1:1", text: "In the beginning God created the heaven and the earth." },
  { ref: "Psalm 23:4", text: "Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me." },
  { ref: "Psalm 121:1", text: "I will lift up mine eyes unto the hills, from whence cometh my help." },
  { ref: "Matthew 28:19", text: "Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost." },
  { ref: "Romans 10:9", text: "That if thou shalt confess with thy mouth the Lord Jesus, and shalt believe in thine heart that God hath raised him from the dead, thou shalt be saved." },
  { ref: "John 11:35", text: "Jesus wept." },
  { ref: "1 Corinthians 16:14", text: "Let all your things be done with charity." },
  { ref: "Colossians 3:23", text: "And whatsoever ye do, do it heartily, as to the Lord, and not unto men." },
  { ref: "Philippians 4:4", text: "Rejoice in the Lord alway: and again I say, Rejoice." },
  { ref: "2 Thessalonians 3:3", text: "But the Lord is faithful, who shall stablish you, and keep you from evil." },
  { ref: "Revelation 3:20", text: "Behold, I stand at the door, and knock: if any man hear my voice, and open the door, I will come in to him, and will sup with him, and he with me." },
  { ref: "Psalm 19:1", text: "The heavens declare the glory of God; and the firmament sheweth his handywork." },
  { ref: "Psalm 19:14", text: "Let the words of my mouth, and the meditation of my heart, be acceptable in thy sight, O Lord, my strength, and my redeemer." },
  { ref: "Matthew 7:7", text: "Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you." },
  { ref: "Matthew 5:9", text: "Blessed are the peacemakers: for they shall be called the children of God." },
  { ref: "Jeremiah 33:3", text: "Call unto me, and I will answer thee, and shew thee great and mighty things, which thou knowest not." },
  { ref: "Proverbs 18:10", text: "The name of the Lord is a strong tower: the righteous runneth into it, and is safe." },
  { ref: "Psalm 23:6", text: "Surely goodness and mercy shall follow me all the days of my life: and I will dwell in the house of the Lord for ever." },
  { ref: "Isaiah 53:5", text: "But he was wounded for our transgressions, he was bruised for our iniquities: the chastisement of our peace was upon him; and with his stripes we are healed." },
  { ref: "Psalm 145:18", text: "The Lord is nigh unto all them that call upon him, to all that call upon him in truth." },
  { ref: "Matthew 4:4", text: "But he answered and said, It is written, Man shall not live by bread alone, but by every word that proceedeth out of the mouth of God." },
  { ref: "John 15:5", text: "I am the vine, ye are the branches: He that abideth in me, and I in him, the same bringeth forth much fruit: for without me ye can do nothing." },
  { ref: "Romans 15:13", text: "Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through the power of the Holy Ghost." },
  { ref: "Psalm 37:5", text: "Commit thy way unto the Lord; trust also in him; and he shall bring it to pass." },
  { ref: "John 3:17", text: "For God sent not his Son into the world to condemn the world; but that the world through him might be saved." },
  { ref: "Ephesians 2:8", text: "For by grace are ye saved through faith; and that not of yourselves: it is the gift of God." },
  { ref: "Psalm 55:22", text: "Cast thy burden upon the Lord, and he shall sustain thee: he shall never suffer the righteous to be moved." },
  { ref: "Deuteronomy 31:6", text: "Be strong and of a good courage, fear not, nor be afraid of them: for the Lord thy God, he it is that doth go with thee; he will not fail thee, nor forsake thee." },
  { ref: "Psalm 62:1", text: "Truly my soul waiteth upon God: from him cometh my salvation." },
  { ref: "Isaiah 54:17", text: "No weapon that is formed against thee shall prosper; and every tongue that shall rise against thee in judgment thou shalt condemn." },
  { ref: "Matthew 22:37", text: "Jesus said unto him, Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind." },
  { ref: "Colossians 3:15", text: "And let the peace of God rule in your hearts, to the which also ye are called in one body; and be ye thankful." },
  { ref: "Psalm 90:12", text: "So teach us to number our days, that we may apply our hearts unto wisdom." },
  { ref: "John 16:33", text: "These things I have spoken unto you, that in me ye might have peace. In the world ye shall have tribulation: but be of good cheer; I have overcome the world." },
  { ref: "Psalm 127:1", text: "Except the Lord build the house, they labour in vain that build it: except the Lord keep the city, the watchman waketh but in vain." },
  { ref: "Hebrews 13:8", text: "Jesus Christ the same yesterday, and to day, and for ever." },
  { ref: "Luke 1:37", text: "For with God nothing shall be impossible." },
  { ref: "Matthew 5:14", text: "Ye are the light of the world. A city that is set on an hill cannot be hid." },
  { ref: "Psalm 23:2", text: "He maketh me to lie down in green pastures: he leadeth me beside the still waters." },
  { ref: "John 13:34", text: "A new commandment I give unto you, That ye love one another; as I have loved you, that ye also love one another." },
  { ref: "Psalm 51:10", text: "Create in me a clean heart, O God; and renew a right spirit within me." },
  { ref: "Ecclesiastes 3:1", text: "To every thing there is a season, and a time to every purpose under the heaven." },
  { ref: "Romans 8:38", text: "For I am persuaded, that neither death, nor life, nor angels, nor principalities, nor powers, nor things present, nor things to come." },
  { ref: "Romans 8:39", text: "Nor height, nor depth, nor any other creature, shall be able to separate us from the love of God, which is in Christ Jesus our Lord." },
  { ref: "Proverbs 17:22", text: "A merry heart doeth good like a medicine: but a broken spirit drieth the bones." },
  { ref: "Psalm 150:6", text: "Let every thing that hath breath praise the Lord. Praise ye the Lord." },
  { ref: "Isaiah 12:2", text: "Behold, God is my salvation; I will trust, and not be afraid: for the Lord JEHOVAH is my strength and my song; he also is become my salvation." },
  { ref: "Matthew 6:26", text: "Behold the fowls of the air: for they sow not, neither do they reap, nor gather into barns; yet your heavenly Father feedeth them. Are ye not much better than they?" },
  { ref: "Philippians 3:13", text: "Brethren, I count not myself to have apprehended: but this one thing I do, forgetting those things which are behind, and reaching forth unto those things which are before." },
  { ref: "Philippians 3:14", text: "I press toward the mark for the prize of the high calling of God in Christ Jesus." },
  { ref: "2 Corinthians 5:7", text: "For we walk by faith, not by sight." },
  { ref: "Psalm 33:12", text: "Blessed is the nation whose God is the Lord; and the people whom he hath chosen for his own inheritance." },
  { ref: "Luke 19:10", text: "For the Son of man is come to seek and to save that which was lost." },
  { ref: "1 Samuel 16:7", text: "For the Lord seeth not as man seeth; for man looketh on the outward appearance, but the Lord looketh on the heart." },
  { ref: "Nahum 1:7", text: "The Lord is good, a strong hold in the day of trouble; and he knoweth them that trust in him." },
  { ref: "Malachi 3:10", text: "Bring ye all the tithes into the storehouse, that there may be meat in mine house, and prove me now herewith, saith the Lord of hosts, if I will not open you the windows of heaven, and pour you out a blessing, that there shall not be room enough to receive it." },
  { ref: "Matthew 19:26", text: "But Jesus beheld them, and said unto them, With men this is impossible; but with God all things are possible." },
  { ref: "Psalm 84:11", text: "For the Lord God is a sun and shield: the Lord will give grace and glory: no good thing will he withhold from them that walk uprightly." },
  { ref: "Acts 1:8", text: "But ye shall receive power, after that the Holy Ghost is come upon you: and ye shall be witnesses unto me both in Jerusalem, and in all Judaea, and in Samaria, and unto the uttermost part of the earth." },
  { ref: "Isaiah 43:2", text: "When thou passest through the waters, I will be with thee; and through the rivers, they shall not overflow thee: when thou walkest through the fire, thou shalt not be burned; neither shall the flame kindle upon thee." },
  { ref: "Proverbs 22:6", text: "Train up a child in the way he should go: and when he is old, he will not depart from it." },
  { ref: "Psalm 32:8", text: "I will instruct thee and teach thee in the way which thou shalt go: I will guide thee with mine eye." },
  { ref: "2 Timothy 3:16", text: "All scripture is given by inspiration of God, and is profitable for doctrine, for reproof, for correction, for instruction in righteousness." },
  { ref: "1 John 1:9", text: "If we confess our sins, he is faithful and just to forgive us our sins, and to cleanse us from all unrighteousness." },
  { ref: "Psalm 143:8", text: "Cause me to hear thy lovingkindness in the morning; for in thee do I trust: cause me to know the way wherein I should walk; for I lift up my soul unto thee." },
  { ref: "Matthew 11:30", text: "For my yoke is easy, and my burden is light." },
  { ref: "Romans 6:23", text: "For the wages of sin is death; but the gift of God is eternal life through Jesus Christ our Lord." },
  { ref: "Psalm 100:3", text: "Know ye that the Lord he is God: it is he that hath made us, and not we ourselves; we are his people, and the sheep of his pasture." },
  { ref: "Proverbs 14:29", text: "He that is slow to wrath is of great understanding: but he that is hasty of spirit exalteth folly." },
  { ref: "Galatians 6:9", text: "And let us not be weary in well doing: for in due season we shall reap, if we faint not." },
  { ref: "Psalm 20:7", text: "Some trust in chariots, and some in horses: but we will remember the name of the Lord our God." },
  { ref: "James 1:19", text: "Wherefore, my beloved brethren, let every man be swift to hear, slow to speak, slow to wrath." },
  { ref: "Matthew 5:6", text: "Blessed are they which do hunger and thirst after righteousness: for they shall be filled." },
  { ref: "1 Thessalonians 5:16", text: "Rejoice evermore." },
  { ref: "1 Thessalonians 5:17", text: "Pray without ceasing." },
  { ref: "1 Thessalonians 5:18", text: "In every thing give thanks: for this is the will of God in Christ Jesus concerning you." },
  { ref: "Matthew 18:20", text: "For where two or three are gathered together in my name, there am I in the midst of them." },
  { ref: "1 Corinthians 13:13", text: "And now abideth faith, hope, charity, these three; but the greatest of these is charity." },
  { ref: "2 Corinthians 12:9", text: "And he said unto me, My grace is sufficient for thee: for my strength is made perfect in weakness." },
  { ref: "Psalm 34:8", text: "O taste and see that the Lord is good: blessed is the man that trusteth in him." },
  { ref: "Proverbs 27:17", text: "Iron sharpeneth iron; so a man sharpeneth the countenance of his friend." },
  { ref: "Genesis 50:20", text: "But as for you, ye thought evil against me; but God meant it unto good, to bring to pass, as it is this day, to save much people alive." },
  { ref: "Psalm 138:8", text: "The Lord will perfect that which concerneth me: thy mercy, O Lord, endureth for ever: forsake not the works of thine own hands." },
  { ref: "Romans 12:12", text: "Rejoicing in hope; patient in tribulation; continuing instant in prayer." },
  { ref: "Luke 6:31", text: "And as ye would that men should do to you, do ye also to them likewise." },
  { ref: "Ecclesiastes 4:12", text: "And if one prevail against him, two shall withstand him; and a threefold cord is not quickly broken." },
  { ref: "Psalm 16:8", text: "I have set the Lord always before me: because he is at my right hand, I shall not be moved." },
  { ref: "Hebrews 12:1", text: "Wherefore seeing we also are compassed about with so great a cloud of witnesses, let us lay aside every weight, and the sin which doth so easily beset us, and let us run with patience the race that is set before us." },
  { ref: "Hebrews 12:2", text: "Looking unto Jesus the author and finisher of our faith; who for the joy that was set before him endured the cross, despising the shame, and is set down at the right hand of the throne of God." },
  { ref: "Psalm 37:7", text: "Rest in the Lord, and wait patiently for him: fret not thyself because of him who prospereth in his way, because of the man who bringeth wicked devices to pass." },
  { ref: "2 Corinthians 4:16", text: "For which cause we faint not; but though our outward man perish, yet the inward man is renewed day by day." },
  { ref: "2 Corinthians 4:17", text: "For our light affliction, which is but for a moment, worketh for us a far more exceeding and eternal weight of glory." },
  { ref: "2 Corinthians 4:18", text: "While we look not at the things which are seen, but at the things which are not seen: for the things which are seen are temporal; but the things which are not seen are eternal." },
  { ref: "Matthew 6:21", text: "For where your treasure is, there will your heart be also." },
  { ref: "Psalm 36:7", text: "How excellent is thy lovingkindness, O God! therefore the children of men put their trust under the shadow of thy wings." },
  { ref: "Lamentations 3:22", text: "It is of the Lord's mercies that we are not consumed, because his compassions fail not." },
  { ref: "Lamentations 3:23", text: "They are new every morning: great is thy faithfulness." },
  { ref: "Matthew 5:13", text: "Ye are the salt of the earth: but if the salt have lost his savour, wherewith shall it be salted?" },
  { ref: "1 Corinthians 10:13", text: "There hath no temptation taken you but such as is common to man: but God is faithful, who will not suffer you to be tempted above that ye are able; but will with the temptation also make a way to escape, that ye may be able to bear it." },
  { ref: "Psalm 25:4", text: "Shew me thy ways, O Lord; teach me thy paths." },
  { ref: "Psalm 25:5", text: "Lead me in thy truth, and teach me: for thou art the God of my salvation; on thee do I wait all the day." },
  { ref: "Proverbs 4:23", text: "Keep thy heart with all diligence; for out of it are the issues of life." },
  { ref: "Philippians 2:3", text: "Let nothing be done through strife or vainglory; but in lowliness of mind let each esteem other better than themselves." },
  { ref: "Galatians 5:23", text: "Meekness, temperance: against such there is no law." },
  { ref: "Hosea 6:6", text: "For I desired mercy, and not sacrifice; and the knowledge of God more than burnt offerings." },
  { ref: "John 10:10", text: "The thief cometh not, but for to steal, and to kill, and to destroy: I am come that they might have life, and that they might have it more abundantly." },
  { ref: "Psalm 63:1", text: "O God, thou art my God; early will I seek thee: my soul thirsteth for thee, my flesh longeth for thee in a dry and thirsty land, where no water is." },
  { ref: "Psalm 63:3", text: "Because thy lovingkindness is better than life, my lips shall praise thee." },
  { ref: "Colossians 3:16", text: "Let the word of Christ dwell in you richly in all wisdom; teaching and admonishing one another in psalms and hymns and spiritual songs, singing with grace in your hearts to the Lord." },
  { ref: "Hebrews 6:19", text: "Which hope we have as an anchor of the soul, both sure and stedfast, and which entereth into that within the veil." },
  { ref: "Psalm 147:3", text: "He healeth the broken in heart, and bindeth up their wounds." },
  { ref: "Micah 7:7", text: "Therefore I will look unto the Lord; I will wait for the God of my salvation: my God will hear me." },
  { ref: "Matthew 11:29", text: "Take my yoke upon you, and learn of me; for I am meek and lowly in heart: and ye shall find rest unto your souls." },
  { ref: "Proverbs 11:25", text: "The liberal soul shall be made fat: and he that watereth shall be watered also himself." },
  { ref: "Romans 12:10", text: "Be kindly affectioned one to another with brotherly love; in honour preferring one another." },
  { ref: "James 3:17", text: "But the wisdom that is from above is first pure, then peaceable, gentle, and easy to be intreated, full of mercy and good fruits, without partiality, and without hypocrisy." },
  { ref: "Psalm 28:7", text: "The Lord is my strength and my shield; my heart trusted in him, and I am helped: therefore my heart greatly rejoiceth; and with my song will I praise him." },
  { ref: "Isaiah 55:8", text: "For my thoughts are not your thoughts, neither are your ways my ways, saith the Lord." },
  { ref: "Isaiah 55:9", text: "For as the heavens are higher than the earth, so are my ways higher than your ways, and my thoughts than your thoughts." },
  { ref: "Psalm 5:3", text: "My voice shalt thou hear in the morning, O Lord; in the morning will I direct my prayer unto thee, and will look up." },
  { ref: "Proverbs 12:22", text: "Lying lips are abomination to the Lord: but they that deal truly are his delight." },
  { ref: "Ezra 8:23", text: "So we fasted and besought our God for this: and he was intreated of us." },
  { ref: "John 14:27", text: "Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid." },
  { ref: "1 Timothy 6:12", text: "Fight the good fight of faith, lay hold on eternal life, whereunto thou art also called, and hast professed a good profession before many witnesses." },
  { ref: "Matthew 16:26", text: "For what is a man profited, if he shall gain the whole world, and lose his own soul? or what shall a man give in exchange for his soul?" },
  { ref: "Psalm 73:26", text: "My flesh and my heart faileth: but God is the strength of my heart, and my portion for ever." },
  { ref: "1 Peter 2:9", text: "But ye are a chosen generation, a royal priesthood, an holy nation, a peculiar people; that ye should shew forth the praises of him who hath called you out of darkness into his marvellous light." },
  { ref: "Ecclesiastes 12:13", text: "Let us hear the conclusion of the whole matter: Fear God, and keep his commandments: for this is the whole duty of man." },
  { ref: "2 Chronicles 7:14", text: "If my people, which are called by my name, shall humble themselves, and pray, and seek my face, and turn from their wicked ways; then will I hear from heaven, and will forgive their sin, and will heal their land." },
  { ref: "Matthew 25:40", text: "And the King shall answer and say unto them, Verily I say unto you, Inasmuch as ye have done it unto one of the least of these my brethren, ye have done it unto me." },
  { ref: "Romans 13:10", text: "Love worketh no ill to his neighbour: therefore love is the fulfilling of the law." },
  { ref: "Proverbs 3:7", text: "Be not wise in thine own eyes: fear the Lord, and depart from evil." },
  { ref: "Psalm 4:8", text: "I will both lay me down in peace, and sleep: for thou, Lord, only makest me dwell in safety." },
  { ref: "Luke 12:15", text: "And he said unto them, Take heed, and beware of covetousness: for a man's life consisteth not in the abundance of the things which he possesseth." },
  { ref: "Acts 17:28", text: "For in him we live, and move, and have our being; as certain also of your own poets have said, For we are also his offspring." },
  { ref: "Psalm 121:2", text: "My help cometh from the Lord, which made heaven and earth." },
  { ref: "Hebrews 13:5", text: "Let your conversation be without covetousness; and be content with such things as ye have: for he hath said, I will never leave thee, nor forsake thee." },
  { ref: "Proverbs 10:12", text: "Hatred stirreth up strifes: but love covereth all sins." },
  { ref: "1 John 3:18", text: "My little children, let us not love in word, neither in tongue; but in deed and in truth." },
  { ref: "Matthew 6:25", text: "Therefore I say unto you, Take no thought for your life, what ye shall eat, or what ye shall drink; nor yet for your body, what ye shall put on. Is not the life more than meat, and the body than raiment?" },
  { ref: "Colossians 3:2", text: "Set your affection on things above, not on things on the earth." },
  { ref: "Psalm 24:1", text: "The earth is the Lord's, and the fulness thereof; the world, and they that dwell therein." },
  { ref: "Numbers 6:24", text: "The Lord bless thee, and keep thee." },
  { ref: "Numbers 6:25", text: "The Lord make his face shine upon thee, and be gracious unto thee." },
  { ref: "Numbers 6:26", text: "The Lord lift up his countenance upon thee, and give thee peace." },
  { ref: "Joshua 24:15", text: "And if it seem evil unto you to serve the Lord, choose you this day whom ye will serve; but as for me and my house, we will serve the Lord." },
  { ref: "1 John 5:14", text: "And this is the confidence that we have in him, that, if we ask any thing according to his will, he heareth us." },
  { ref: "Psalm 100:4", text: "Enter into his gates with thanksgiving, and into his courts with praise: be thankful unto him, and bless his name." },
  { ref: "2 Peter 3:9", text: "The Lord is not slack concerning his promise, as some men count slackness; but is longsuffering to us-ward, not willing that any should perish, but that all should come to repentance." }
];

// Deterministic pick for a given day, so the "daily" verse stays the same
// all day and rolls over at midnight. The bar citation and the popup text
// have to agree, so both route through this same index.
function verseForDay(year, month, day) {
  if (!VERSES || VERSES.length === 0) return { ref: "", text: "" }
  var key = (year * 372 + (Number(month) + 1) * 31 + Number(day))
  var index = key % VERSES.length
  return VERSES[index]
}
